import adobexd from '../images/skills/adobexd.svg';
import css from '../images/skills/css.svg';
import docker from '../images/skills/docker.svg';
import express from '../images/skills/express.svg';
import figma from '../images/skills/figma.svg';
import firebase from '../images/skills/firebase.svg';
import git from '../images/skills/git.svg';
import github from '../images/skills/github.svg';
import golang from '../images/skills/go.svg';
import gradle from '../images/skills/gradle.svg';
import groovy from '../images/skills/groovy.svg';
import grpc from '../images/skills/grpc.svg';
import html from '../images/skills/html.svg';
import java from '../images/skills/java.svg';
import javafx from '../images/skills/javafx.png';
import javascript from '../images/skills/javascript.svg';
import kafka from '../images/skills/kafka.svg';
import mongodb from '../images/skills/mongodb.svg';
import mySQL from '../images/skills/mysql.svg';
import nestjs from '../images/skills/nestjs.svg';
import nodejs from '../images/skills/nodejs.svg';
import postgreSQL from '../images/skills/postgresql.svg';
import python from '../images/skills/python.svg';
import react from '../images/skills/react.svg';
import redis from '../images/skills/redis-icon.svg';
import redux from '../images/skills/redux.svg';
import socketIo from '../images/skills/socketio.svg';
import spring from '../images/skills/spring.svg';
import typescript from '../images/skills/typescript.svg';
import flow from '../images/skills/flow.png';
import hack from '../images/skills/hack.svg';
import php from '../images/skills/php.svg';
import swift from '../images/skills/swift.png';
import relay from '../images/skills/relay.svg';
import graphQL from '../images/skills/graphql.svg';

export const javaIcon = { icon: java, name: 'Java' };
export const springIcon = { icon: spring, name: 'Spring Boot' };
export const grpcIcon = { icon: grpc, name: 'gRPC', height: '1.5em' };
export const postgreSQLIcon = { icon: postgreSQL, name: 'PostgreSQL' };
export const reactIcon = { icon: react, name: 'React' };
export const jsIcon = { icon: javascript, name: 'JavaScript' };
export const nodeJsIcon = { icon: nodejs, name: 'Node.js' };
export const expressIcon = { icon: express, name: 'Express.js' };
export const kafkaIcon = { icon: kafka, name: 'Apache Kafka' };
export const dockerIcon = { icon: docker, name: 'Docker', height: '1.7em' };
export const firebaseIcon = { icon: firebase, name: 'Firebase' };
export const pythonIcon = { icon: python, name: 'Python' };
export const cssIcon = { icon: css, name: 'CSS' };
export const htmlIcon = { icon: html, name: 'HTML' };
export const adobeXdIcon = { icon: adobexd, name: 'Adobe XD' };
export const javaFxIcon = { icon: javafx, name: 'JavaFX' };
export const figmaIcon = { icon: figma, name: 'Figma' };
export const mongodbIcon = { icon: mongodb, name: 'MongoDB' };
export const socketIcon = { icon: socketIo, name: 'socket.io' };
export const gitIcon = { icon: git, name: 'Git' };
export const githubIcon = { icon: github, name: 'GitHub' };
export const gradleIcon = { icon: gradle, name: 'Gradle' };
export const groovyIcon = { icon: groovy, name: 'Groovy' };
export const goIcon = { icon: golang, name: 'Go', height: '1.1em' };
export const tsIcon = { icon: typescript, name: 'TypeScript' };
export const nestIcon = { icon: nestjs, name: 'NestJS' };
export const mySQLIcon = { icon: mySQL, name: 'MySQL', height: '1.8em' };
export const reduxIcon = { icon: redux, name: 'Redux' };
export const redisIcon = { icon: redis, name: 'Redis' };
export const flowIcon = { icon: flow, name: 'Flow' };
export const hackIcon = { icon: hack, name: 'Hack', height: '2em' };
export const phpIcon = { icon: php, name: 'PHP', height: '2em' };
export const swiftIcon = { icon: swift, name: 'Swift', height: '2.5em' };
export const relayIcon = { icon: relay, name: 'Relay', height: '2.5em' };
export const graphQLIcon = { icon: graphQL, name: 'GraphQL' };
